{% set name = "pyroll-report" %}
{% set version = "3.0.0.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyroll_report-{{ version }}.tar.gz
  sha256: 80d891dadeb6953407f6d3c79558258bf4a4a03f477ac8f1effd828e0cf8adf6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - pyroll-core >=3.0,<4.dev0
    - matplotlib-base >=3.6,<4.dev0
    - jinja2 >=3.0,<4.dev0
    - pluggy >=1.0,<2.dev0

test:
  imports:
    - pyroll.report
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pyroll.readthedocs.io
  summary: PyRoll rolling simulation framework - HTML report generation.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
